# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='cs_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='cs_uri_query',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='cs_uri_stem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='cs_user_agent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='cs_username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='lognum',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='s_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
