# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0002_auto_20170929_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='cs_uri_query',
            field=models.CharField(max_length=200),
        ),
    ]
