# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0004_auto_20170929_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='cs_uri_query',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='cs_user_agent',
            field=models.CharField(max_length=1000),
        ),
    ]
