# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0005_auto_20170929_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='c_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='s_port',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='sc_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='sc_substatus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='sc_win32_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
    ]
