# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0006_auto_20170930_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='ip_city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='logdata',
            name='ip_region',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
