# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0007_auto_20171009_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='time',
            field=models.TimeField(max_length=200),
        ),
    ]
