# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0010_auto_20171018_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnet',
            name='net',
            field=models.CharField(max_length=100),
        ),
    ]
