# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0012_auto_20171019_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncount',
            name='logdatename',
            field=models.CharField(max_length=100),
        ),
    ]
