# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logana', '0013_auto_20171019_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('ip_message', models.TextField(max_length=30000)),
                ('page_massage', models.TextField(max_length=30000)),
            ],
        ),
    ]
